### ISSUE TITLE
Parsing fails with ArrayIndexOutOfBoundsException on slightly malformed UA

### ISSUE THREAD

**Issue by jgetto** [udger/udger-java#18]
Attempting to parse this UA, which appears to have a malformed browser version: 

```
Mozilla/4.0 (Windows NT 6.1; rv:..; Gecko/20100403; Trident/4.0; Maxthon; SV1;  .NET CLR 1.1.4322; .NET CLR 3.0.04320; Firefox/..; FirePHP/3.8)
```

Results in 

```
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.udger.parser.UdgerParser.patchVersions(UdgerParser.java:669)
	at org.udger.parser.UdgerParser.clientDetector(UdgerParser.java:465)
	at org.udger.parser.UdgerParser.parseUa(UdgerParser.java:198)
```

I would expect this to result in an unknown/blank version

**Comment by skybber** [comment]
Fixed
