### ISSUE TITLE
Udger throwing exception

### ISSUE THREAD

**Issue by rblin081** [udger/udger-java#3]
Udger is throwing the following exception

 java.sql.SQLException: [SQLITE_CORRUPT]  The database disk image is malformed (database disk image is malformed)
	at org.sqlite.core.DB.newSQLException(DB.java:890)
	at org.sqlite.core.DB.newSQLException(DB.java:901)
	at org.sqlite.core.DB.execute(DB.java:810)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:68)
	at tcorej.util.http.useragent.UdgerDataCache$UdgerParser.getFirstRow(UdgerDataCache.java:280)
	at tcorej.util.http.useragent.UdgerDataCache$UdgerParser.parseUa(UdgerDataCache.java:151)
	at tcorej.util.http.useragent.UdgerDataCache$1.load(UdgerDataCache.java:46)
	at tcorej.util.http.useragent.UdgerDataCache$1.load(UdgerDataCache.java:40)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875)

**Comment by skybber** [comment]
Caused by Sqlite driver used on NFS.
