### ISSUE TITLE
NPE at org.udger.parser.LRUCache$Node.access$202(LRUCache.java:14)

### ISSUE THREAD

**Issue by nitsandaniel** [udger/udger-java#8]
I'm getting many errors while using the client with cache, relevant stack trace: 
```
! java.lang.NullPointerException: null
! at org.udger.parser.LRUCache$Node.access$202(LRUCache.java:14)
! at org.udger.parser.LRUCache.get(LRUCache.java:57)
! at org.udger.parser.UdgerParser.parseUa(UdgerParser.java:144)
```

**Comment by skybber** [comment]
UdgerParser is not thread safe, are you using multi thread access for single parser?
